### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rapgro** [OpenFodder/openfodder#1]
Would like to see some package in Fedora (or any other Linux distribution). Therefore, this source needs a valid FLOSS license. We recommend to use GPLv3.

**Comment by skitt** [comment]
The source code itself includes appropriate GPL license headers, although the text of the GPL license itself is missing (as per the license headers, it should be provided in the source code).

To make this available in a distribution though it would be necessary to know the licensing situation of the various WAV files. I'm guessing the magazine cover disks (Amiga Power #31 and Amiga Format Christmas Special) won't be distributable in Linux distributions...

**Comment by segrax** [comment]
I'll be looking at putting the proper license text file in shortly, but I do need to sort out 'dernc.cpp' (https://github.com/segrax/openfodder/blob/master/Source/Amiga/dernc.cpp).. its currently using the BSD license - its taken from another repo... source is provided in the header.

The WAV files probably should never of been put into the repository, without the Amiga music though.. the DOS version is kind-of... not as much fun :)
But anyway, they will be removed at some point... unless we can somehow get permission to release them... although given the Amiga version has been off shelf for ~20 years, that probably wont be an easy task (does Virgin own the rights to the Amiga version?)

I was under the impression the Magazine cover disks where considered free demos, although if not... i will also remove them, most likely this will result in adding ADF support sooner, so its easier to rip the original disks and play them.

**Comment by rapgro** [comment]
Thanks for the FLOSS clarification that means a green light for Linux distributions. 
Indeed, GPL requires to include the license text not only in the file headers but also as a separate file with the complete text, otherwise distributions get a problem with relicensing. Dual license as GPL and BSD is no problem, a license can be restricted to individual files. In case of Linux (for PC), is that Amiga source even of any relevance?
The proprietary music files shouldn't be an issue if you can provide them in a separate 3rdparty tarball. Otherwise, those files need to be excluded or in prior removed from the maintained packages.

**Comment by rapgro** [comment]
https://github.com/segrax/openfodder/commit/c82cd1140123b4dfd440582c49dd084b56063c09#diff-abcb5e872fde7c4deecc432bc7628c1a

Thanks!
