### ISSUE TITLE
Need help compiling and running game

### ISSUE THREAD

**Issue by Shoes01** [OpenFodder/openfodder#15]
I was surprised to find an Open project on Cannon Fodder, and more surprised still to see it past 1.0! Congratulations.

I can't seem to find any instructions (or discussion) about this game or how to compile it. When I run the .exe in VS2017, I get `The program '[12304] OpenFodder.exe' has exited with code 1 (0x1).`. 

Here is the whole output, if that helps.

> 'OpenFodder.exe' (Win32): Loaded 'C:\Users\jason.gilbert\Downloads\openfodder-1.4.0\openfodder-1.4.0\Run\OpenFodder.exe'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Users\jason.gilbert\Downloads\openfodder-1.4.0\openfodder-1.4.0\Run\SDL2_mixer.dll'. Module was built without symbols.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Users\jason.gilbert\Downloads\openfodder-1.4.0\openfodder-1.4.0\Run\SDL2.dll'. Module was built without symbols.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. Symbols loaded.
> 'OpenFodder.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. Symbols loaded.
> The thread 0x20 has exited with code 1 (0x1).
> The thread 0x3918 has exited with code 1 (0x1).
> The thread 0x39a4 has exited with code 1 (0x1).
> The program '[12304] OpenFodder.exe' has exited with code 1 (0x1).

I don't have much experience, so any help would be appreciated!

**Comment by segrax** [comment]
Hey,

Do you have the required data download unpacked into the Run folder? (if so, it would appear some work is needed on error messages)

https://github.com/OpenFodder/data/releases/download/1.4/OpenFodder.zip

Essentially Run should look like this
Run\Data, Run\Campaigns, Run\Saves

Alternatively, you can unpack it as is to your 'Documents' folder (c:\users\<your user>\Documents).

**Comment by Shoes01** [comment]
I had none of the data download! And on my second look over, I still don't really see any mention of it. 

Unpacking that into the Run folder did indeed fix the problem. I have the GoG version downloaded; I dumped all the .bin and .dat files into Data\Dos_CD and that seemed to work. That seems to work too.

**Comment by segrax** [comment]
Yeah, our documentation is somewhat lacking :)

It is mentioned in the readme, but the readme itself needs improvements to make it easier to read

**Comment by Shoes01** [comment]
Right, I see it now. I skimmed over the Campaign Data part, thinking "I bought the game, this won't be needed". I was evidently wrong!

**Comment by segrax** [comment]
Originally you didnt, but to add support for custom campaigns it was the easieset way forward to seperate the original mission information out of the executable
