### ISSUE TITLE
Compilation on linux + a couple of questions

### ISSUE THREAD

**Issue by sheepo99** [OpenFodder/openfodder#19]
Hello there,

First and foremost, thank you very much for creating this project! Cannon Fodder was one of my favorites back in the Amiga days, and probably one of the games I sunk the most time in during my youth, along with two other classics, Sensible Soccer and Chaos Engine. It's great to have it available again under a free software engine, along with a map editor!

I've been previously running OpenFodder on Windows, but I would like to know if it would be possible for you to provide compilation instructions for Linux. Currently there is no documentation specifying the required libraries and additional instructions for compilation, and I think it would be nice if these could be included in the readme or a separate file.

Secondly I would know if a universal Linux Snap/AppImage package could be provided for future stable builds.

Thirdly, and as a more impertinent request, since you've done such a great work with Cannon Fodder, any chance you can eventually give a similar treatment to Sensible World of Soccer? There's still a huge community playing the game online, mostly using shaky emulators with poor multiplayer capability, and an free software port for it would certainly be more than welcome!

That's it for today. Please continue the amazing work and a have a nice day!

**Comment by segrax** [comment]
Hey,

You're welcome, the same goes for us, CF is a great game and this project has been a ton of fun (and annoyance at times too :)

We certainlly can help out with that, its been on our un-written "TODO" for awhile now.. just other priorities usually bump it. Will try to spend some time on some Linux doco over the next week or two

In the mean time, a fresh install of ubuntu should only require the following to get it building
`
sudo apt-get install clang libsdl2-dev libsdl2-mixer-dev
make
`

the built executable should be in the 'Run' directory.

A package would be great, unfortunately I just don't have the time required to create or maintain it (but we're happy to support anyone else wanting to do so)

While I definately enjoy porting old games, it does take a considerable amount of time... something which im unfortauntely lacking these days, if that does change in the near future, ill keep this request in mind :)

**Comment by sheepo99** [comment]
Hi again,

Thanks! So far I've been trying to compile the stable and the latest source package. I'm getting the following errors using the cmd line you posted above verbatim:

Stable:
/usr/bin/ld: cannot open output file Run/OpenFodder: Is a directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:12: recipe for target 'fodder' failed
make: *** [fodder] Error 1

Latest source package:
1 warning generated.
Makefile:16: recipe for target 'main' failed
make: *** [main] Error 1

Any help? Kind regards and have a nice day!

**Comment by segrax** [comment]
Whats the contents of the Run folder? it appears there is a directory named 'OpenFodder' in there, which is causing link to fail

**Comment by sheepo99** [comment]
Thanks! That was indeed the issue. It's compiling fine now.

One more question, is there any command to make the game run in windowed mode?

**Comment by segrax** [comment]
> One more question, is there any command to make the game run in windowed mode?

No, but if you compile with the define _DEBUG; it will launch in window mode

I will also add this feature to the TODO list, it could probably benefit others

**Comment by drnovice** [comment]
Of course you can use F11 and +/- keyboard keys respectively to toggle fullscreen and zoom in/out window at runtime.

**Comment by segrax** [comment]
Done,

You can now specify -w or --window on CLI to start in window mode

**Comment by segrax** [comment]
Also, have added some other options, you can view using -h or --help
