### ISSUE TITLE
to release 1.0

### ISSUE THREAD

**Issue by drnovice** [OpenFodder/openfodder#2]
Both x86 and x64 built:
By CF1 stuff, Amiga version:
1) Missing Animation into Briefing Screen (helicopter landing)
2) Heroes and Squad writings into Hill Screen are like dos appearence instead original amiga appearence.
3) Soldiers animation into Hill Screen goes wrong (first soldiers don't get down from the footpath)
4) On Save Screen, the prompt cursor is corrupted (it shows another part of sprite sheets, seems some people sprites)
5) On Load Screen the writings don't have square red/green borders

By CF2 stuff, DOS version:
1) No sound (maybe a wrong my configuration?)
2) "Try Again" animation has half ufo sprite on the right of the writing
3) Briefing Screen on first missions (middle-east) don't have to have the ufo landing
4) Is there a somersaulted car on extreme right of level 1 (Map1)?!?

**Comment by segrax** [comment]
2, 3 are now fixed

**Comment by drnovice** [comment]
Are you ok if you split release into:
a) v1.0: all CF1 Dos version ok
b) v1.1: all CF1 Amiga version and other stuff ok
c) v2.0: all CF2 Dos version ok
d) v2.1: all CF2 Amiga version ok

So v1.0 for CF1 Dos stuff can be now released!

**Comment by segrax** [comment]
Sounds like a workable approach, i might take care of #4/#5 first though.. they're pretty simple

**Comment by drnovice** [comment]
Sure

**Comment by segrax** [comment]
All good for

**Comment by segrax** [comment]
32 bit?

**Comment by drnovice** [comment]
x64 issues are the same than on x86.

**Comment by pfaltynek** [comment]
I have tried to build and test using the DOS data (CF_ENG.DAT) on 64bit Arch linux:
1. Unable to load saved position - it is not shown in save files list but the save file exists.
2. When playing the Amiga demo (5 stages) and thow an grenade onto the green house the application closes itself (probably due the crash).
3. The keyboard bufer should be cleared before the screen to enter the save file name appears.
I have seen the M appeared in it but I did not pressed any key yet - the M key has been pressed in map mode to close it insead of the click on the map (my mistake).

**Comment by LanceJZ** [comment]
On the 64bit Windows version 1.0 when I blew up a hut with a grenade the game crashed.

**Comment by segrax** [comment]
Seems the Cannon Fodder Plus sounds are different to all other versions.. hmm

**Comment by q4a** [comment]
Build and tested 1.0 on Ubuntu 15.10 amd64 with DOS data (CF_ENG.DAT):
1. Same: Unable to load saved position - it is not shown in save files list but the save file exists.
2. When playing the Cannon Fodder Plus stage 3, go to top right corner and thow an grenade onto the green house the game closes itself: Segmentation fault (core dumped)

**Comment by segrax** [comment]
@q4a Thanks, i've just fixed save game loading in Trunk, and disabled the grenade sound for now... 
it has some issue, and i'm not sure if the sound format is different between the final release and the demo.... or the file is corrupt, either way.. until a proper solution is found, no grenade sound :)

**Comment by segrax** [comment]
@pfaltynek 1/2 are fixed (well.. 2 is kind of fixed). and i couldn't replicate 3, but I've made some changes which should ensure that can't happen anyway

**Comment by q4a** [comment]
@segrax Thanks, I tested again: last commits fix problems.
