### ISSUE TITLE
Current master can't compile on Linux

### ISSUE THREAD

**Issue by xcom169** [OpenFodder/openfodder#21]
Current master can't compile on Linux with C++ compiler

**Comment by segrax** [comment]
Hey,

What error are you seeing?

The current master is building ok with [TravisCi ](https://travis-ci.org/OpenFodder/openfodder)

**Comment by drnovice** [comment]
Did you install sdl libraries?

**Comment by xcom169** [comment]
> Hey,
> 
> What error are you seeing?
> 
> The current master is building ok with [TravisCi ](https://travis-ci.org/OpenFodder/openfodder)

Yes,
Source/Fodder.cpp:16243:52: error: ordered comparison between pointer and zero ('sMission_Troop *' and 'int')
            if (pSprite->field_5E_SoldierAllocated >= 0) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~
2 warnings and 1 error generated.

**Comment by segrax** [comment]
I'll change that later, but have you altered the compile flags?

as the current master is still building with default makefile on travis ci

**Comment by xcom169** [comment]
> I'll change that later, but have you altered the compile flags?
> 
> as the current master is still building with default makefile on travis ci

I didn't change the compile flags. 
Now it seems to be okay on Ubuntu 18.04.

Thanks! This can be closed.
