### ISSUE TITLE
Is there any way to debug the executable in runtime?

### ISSUE THREAD

**Issue by xcom169** [OpenFodder/openfodder#23]
Is there any way to debug the C++ code, or the executable file in Linux to see when what's happening? 
I'd like to see in which files are being read, written so on?
In eg. Python it is possible to go line by line during runtime.

**Comment by segrax** [comment]
Yeah, 
VSCode can debug on Linux similar to Visual Studio on Windows, excluding the 'Edit & Continue' feature

![image](https://user-images.githubusercontent.com/1327406/46721620-2e281a00-ccbf-11e8-9999-c6ca026dbbc7.png)


You just need to add '-g' to the CC flags in the makefile, and after running make, you can launch it with VSCode and set breakpoints in the GUI
