### ISSUE TITLE
OpenFodder.exe only runs as Admin on Windows 7

### ISSUE THREAD

**Issue by xcom169** [OpenFodder/openfodder#25]
OpenFodder.exe only runs as Admin on Windows 7
Why admin rights are needed?

**Comment by segrax** [comment]
It doesn't,

but if you used the installer as admin, it will have installed the data into the admin users Documents folder... which does probably need changing by the sound of it ;)

![image](https://user-images.githubusercontent.com/1327406/46909880-9576f000-cf85-11e8-9902-a6acd2cc133f.png)

**Comment by segrax** [comment]
today we have overhauled the resource system, and altered the installer to allow installing to program directory instead of documents folder,
if you install to program directory, you should be right to run without admin
