### ISSUE TITLE
[windows] Get data from program directory

### ISSUE THREAD

**Issue by mstempell** [OpenFodder/openfodder#26]
It would be great if OpenFodder could get its data from the directory it's in on Windows.

Currently, if i try to put the `Campains/`, `Data/` and `Save/` directories in the same path where `OpenFodder.exe` is, the program starts, but it only shows custom campaigns and then even cannot starts one of those custom levels (direct death).

*The Windows setup i am using on this is XP based. But as the program runs up to the menu (with full action there), i don't think XP would be the cause of this.*

Thanks in advance, and for all your work on this. :thumbsup:

**Comment by segrax** [comment]
Hey there,

Thanks for the report,

I don't have an XP machine setup to do any testing at this point, but are you able to verify if you removed the 'OpenFodder' folder from the Documents folder?

The behaviour of the game (on Windows) should be like this on this startup

1. Check for %USERPROFILE%/Documents/OpenFodder
2. Check current directory 
3. Quit out with error about missing data

This setup should work fine:
![image](https://user-images.githubusercontent.com/1327406/50058461-b4d00a80-01cc-11e9-9fc8-cf956b6c4c0a.png)


Although in either case, i must admit this area of the engine does need work, as its a very hacky solution at this point in time :)

**Comment by mstempell** [comment]
Thanks for your answer segrax.

The %USERPROFILE%/Documents/OpenFodder doesn't exist on the system.
Also the game folder layout is exactly like yours.

So i tried several things.

The program actually detects the data correctly, as the available campaigns list (from `--list-campaigns` command line option) change with and without original data added.

Also, if i starts the program with the campaign selection command line option to select a specific campaigns (like `-c "Cannon Fodder"`), that one starts correctly and i can play it.

So it seems that only the menu is not listing all available campaigns.

Here is a screenshot of the menu i get with all possible game data added: https://i.imgur.com/0aqMcMA.png

**Comment by segrax** [comment]
Thanks @mstempell 

Ill setup XP in a VM at some point over the next day or two and hopefully it will replicate for me.

interesting issue, but there is some crap going on between generating the actual list, and the list displayed on that menu... hopefully the problem is in that :)

Cheers,
Rob

**Comment by segrax** [comment]
ok, installed XP in VM... and unable to replicate it :/

![image](https://user-images.githubusercontent.com/1327406/50147200-a5a2a700-0309-11e9-92ef-c50b89cd9dd1.png)

**Comment by segrax** [comment]
@mstempell the only thing i can think of,

Did the files inside the Campaigns folder extract with spaces?

i doubt this is the issue, because im still not able to replicate your exact scenario with it (i cant launch even from the CLI, if i rename my campaign files)

kind of at a loss about what we can look at next here

**Comment by mstempell** [comment]
Thanks for putting up a VM to test this, much appreciated.

The campaign files (.ofc) got proper spaces in names when extracted.

But if i try renaming the campaigns files to:
```
AmigaAction.ofc
AmigaFormatChristmasSpecial.ofc
AmigaFormatNotVeryFestive.ofc
AmigaTheOne.ofc
CannonFodder.ofc
CannonFodder2.ofc
CannonFodderPlus.ofc
PCFormat.ofc
segras.ofc
```
Then all campaigns show up in the list (but without space in their name so based on the files names).

_But when i then try to start any campaign from the list, it always show Cannon Fodder (1) intro, and the actual level started (despite its level name changing) is always first Cannon Fodder (1) level.
It's probably just messed up due to the space-less files names._

**Comment by segrax** [comment]
have you got any other system you can test with (even a VM?), 

its' really puzzling, i cant think of any scenarios where the campaign screen would be empty, but the game can launch from CLI.. both cases depend on the same data requirements

Here we check if available, or if its the single/random option, then add to the list
https://github.com/OpenFodder/openfodder/blob/master/Source/Fodder.cpp#L4046


actually, is your windows running in a non-english language or anything like that?

**Comment by mstempell** [comment]
> actually, is your windows running in a non-english language or anything like that?

Ah yes i do, it's a french Windows XP.

Maybe a build with debug log on the puzzling code, that i could run, could give hint?

I'll test with on some Windows 7 PC when i can (French too).

**Comment by mstempell** [comment]
OK not reproduced on (French) Windows 7.

It's most probably something about the way directories with spaces get (not) listed on the problematic OS.

**Comment by segrax** [comment]
Ok thanks,

I'll track down a non-english XP and see if we can solve this issue

Cheers!

**Comment by mstempell** [comment]
Or maybe it is about how campaigns titles block are generated for the list ?

**Comment by segrax** [comment]
Hi @mstempell 

Just wondering if this problem still occurs for you with the latest build? (https://s3.amazonaws.com/openfodder-builds/OpenFodder-latest.zip)

**Comment by mstempell** [comment]
Hello,
I tried with the build available there today and, sorry to say, it works even less.

Result of `--list-campaigns` now gives :
```
d:\Games\OpenFodder>OpenFodder.exe --list-campaigns

d:\Games\OpenFodder>
Available Campaigns


No game data could be found, including the demos, have you installed the data pack?
We are looking for the 'Data' directory in:
d:\Games\OpenFodder
C:\Documents and Settings\Mathieu/Documents/OpenFodder/
Press enter to quit

d:\Games\OpenFodder>dir
 Le volume dans le lecteur D s'appelle WORK
 Le numéro de série du volume est 34ED-6F49

 Répertoire de d:\Games\OpenFodder

23/03/2019  11:36    <REP>          .
23/03/2019  11:36    <REP>          ..
19/12/2018  21:59    <REP>          Campaigns
01/04/2019  09:52            35 147 COPYING
17/12/2018  22:55    <REP>          Data
09/11/2018  12:38           245 248 libmodplug-1.dll
01/04/2019  09:53         1 340 416 OpenFodder.exe
01/04/2019  09:52             5 968 README.md
17/12/2018  22:55    <REP>          Saves
09/11/2018  12:38         1 088 000 SDL2.dll
09/11/2018  12:38           119 296 SDL2_mixer.dll
               6 fichier(s)        2 834 075 octets
               5 Rép(s)   2 200 403 968 octets libres

d:\Games\OpenFodder>
```

**Comment by segrax** [comment]
Thanks @mstempell,

unfortunately i haven't yet got a non-english XP, 
@drnovice apparently has an italian one, but has been occupied by the real world :) 

Hopefully we can get some time to debug it soon,

most of the existing resource management system was rewritten this year, which resolved *most* of the issues people faced.. except this one seemingly...

**Comment by segrax** [comment]
Since the last post on this issue, the resource system has been completely re-written, and multiple sources can now be defined in the INI file.

If this issue is still persisting, feel free to reopen!
