### ISSUE TITLE
1.5.3 segfault on OpenBSD

### ISSUE THREAD

**Issue by ibara** [OpenFodder/openfodder#27]
**Describe the bug**
OpenFodder 1.5.3 segfaults after clicking on Cannon Fodder from the main menu. GDB backtrace attached.
Additionally (though perhaps unrelated) Cannon Fodder 2 does not appear in the list despite having CF_ENG.DAT from CF2 in $HOME/.local/OpenFodder/Data/Dos2_CD

**To Reproduce**
1. Build OpenFodder 1.5.3
2. Launch it
3. Click on Cannon Fodder on main menu

**Expected behavior**
Game loads.

**Desktop (please complete the following information):**
 - OS: OpenBSD
 - Version 6.4-current

[openfodder.log](https://github.com/OpenFodder/openfodder/files/2713984/openfodder.log)

**Comment by segrax** [comment]
Thanks Brian

I'll take a look when i've got some free time again

**Comment by ibara** [comment]
No rush, appreciated.

**Comment by segrax** [comment]
hey @ibara 

is this still occurring with the latest master? 

i've been unable to replicate your crash, 
although a few people have had issues with the CF2 detection, it seems mostly related to upper/lower casing on filenames. i'll need to look into another solution for that

**Comment by ibara** [comment]
Also can't reproduce so something fixed it along the way.
I'll wait for a new release to update the OpenBSD package.

**Comment by segrax** [comment]
Closing as we unable to replicate
