### ISSUE TITLE
Libretro support?

### ISSUE THREAD

**Issue by bam80** [OpenFodder/openfodder#29]
Thank you very much for bringing back such a beautiful game for us!

**Comment by segrax** [comment]
You're most welcome.

This library is interesting, thanks for bringing it to my attention!!

That being said, can make no promises, but we will certainly consider it

**Comment by segrax** [comment]
@bam80 i've taken a look, and it will unfortunately this will take significant effort to use this library.

CF engine has never ending loops, inside never ending loops.. and the retro library requires a return after each cycle :( 
it just wont be possible without redesigning how the engine works, which im not against, but dont really have the time to do at the moment

**Comment by bam80** [comment]
OK, thanks for looking anyway

**Comment by segrax** [comment]
Closing as implementing isnt really feasible in the short term
