### ISSUE TITLE
Separated user and program directory

### ISSUE THREAD

**Issue by Mailaender** [OpenFodder/openfodder#3]
A `make install` routine which would install things into
- /usr/bin/openfodder
- /usr/share/openfodder

and store save games as well as game data in user writable standardized folders as specified by https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html would be great.

**Comment by Mailaender** [comment]
I hacked things around at https://build.opensuse.org/request/show/367032 with a wrapper script.

**Comment by segrax** [comment]
Hi @Mailaender 

Appologies for the large delay in response; But we are finally starting to head towards this.

The run folder will be removed from this repository soon, as a Windows installer will be created (and whichever OS anyone else creates one for), and possibly a built-in mechanism for downloading the Demo data files, as well as user uploaded custom maps/missions.

**Comment by segrax** [comment]
The Data has now been seperated out, environment variable XDG_DATA_DIRS is iterated for the 'OpenFodder' folder, which should contain the data/campaign information from our https://github.com/OpenFodder/data repository. If it does not, $HOME/.local/share will be checked.

Failing that, the current directory will be checked
