### ISSUE TITLE
openfodder fails to compile under Gentoo Linux

### ISSUE THREAD

**Issue by VonKossa** [OpenFodder/openfodder#30]
Installed requiered libs and i know 1.30 and 1.3.1 built correctly.
When compiling 1.5.3 i get:

git log -n 1 --pretty="const char* gitversion=\"%%h\";" > ./Source/gitver.hpp
fatal: not a git repository (or any parent up to mount point /mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
make: *** [Makefile:16: main] Error 128

**Comment by segrax** [comment]
Hi VonKossa,

oversight on our part, 
we assumed that anyone compiling would use git clone to check out the code

Thanks for report

**Comment by VonKossa** [comment]
But i did not even touch the repository, i downloaded the 1.5.3 release.

________________________________

**Comment by segrax** [comment]
yeah,

the release source package doesn't contain the ".git" directory, and the makefile is attempting to run git, for the purpose of exporting the hash from it

**Comment by VonKossa** [comment]
Great, thanks! Worked like a charm to clone the git repo.

**Comment by segrax** [comment]
We will get this fixed soon, 

the change requiring git was a last minute thing before release, just so we could include the repository hash in the 'about' screen

**Comment by LiamDawe** [comment]
Hi, this is a problem again with the latest release source package.

**Comment by segrax** [comment]
> 
> 
> Hi, this is a problem again with the latest release source package.

Hi Liam,
What error are you seeing?

**Comment by LiamDawe** [comment]
Hi, here it is:

> git log -n 1 --pretty="const char* gitversion=\"%%h\";" > ./Source/gitver.hpp
> fatal: not a git repository (or any of the parent directories): .git
> make: *** [Makefile:16: main] Error 128

Worked fine through git clone, the error above when downloading the source package from the tagged release.
