### ISSUE TITLE
Cheats

### ISSUE THREAD

**Issue by daninthemix** [OpenFodder/openfodder#31]
Would it be easy to add e.g. god mode just for fun?

**Comment by segrax** [comment]
Indeed,

in fact it already exists, but is only enabled in the _DEBUG build, if you compile yourself and add _DEBUG define, it will enable

F9 makes your current squad invincible
F10 completes the current map

https://github.com/OpenFodder/openfodder/blob/master/Source/Fodder.cpp#L3186

**Comment by daninthemix** [comment]
Any chance you could add to the final build next time you push changes? I
don't have all the gubbins necessary to compile, and other users might
enjoy these options :)

**Comment by segrax** [comment]
Done,

you can now use --cheats on startup to enable F9/F10

**Comment by daninthemix** [comment]
Thanks. Where can I get the new exe?

**Comment by segrax** [comment]
Latest exe is always here:

https://s3.amazonaws.com/openfodder-builds/OpenFodder-latest.zip

**Comment by daninthemix** [comment]
I have a new cheat request, if its even possible: invincible vehicles / turrets. So easy to fail a mission when the turret or vehicle you require gets destroyed within 2 seconds!

**Comment by segrax** [comment]
Perhaps you would prefer this experience, start the game like this

openfodder --demo-record-all --unit-test

watch what happens when you die :)

**Comment by segrax** [comment]
stay in game a few seconds before you run off the cliff in mission 1 phase 1, otherwise it will just restart the map
