### ISSUE TITLE
Graphics from PC Version, Music from Amiga

### ISSUE THREAD

**Issue by drozumek** [OpenFodder/openfodder#33]
Is it possible to make version which has graphics from PC version (looks better) and music/sound from amiga version (sounds much better)?

**Comment by segrax** [comment]
Sort of,

The dos version already has a music replacement in place, making use of an extract from the Amiga version. However the sound effects remain the same as the original.

it *should* be trivial to replace the entire cSound_PC class with the cSound_Amiga class, it would just require some tweaking to the resource manager to look in the Amiga data path

**Comment by segrax** [comment]
Ok its implemented in the latest commit build,

Place these files from the Amiga release in the Dos_CD folder and all music/sound effects will be replaced

DESBASE.INS
DESBASE.SNG
ICEBASE.INS
ICEBASE.SNG
INTBASE.INS
INTBASE.SNG
JON.INS
JON.SNG
JUNBASE.INS
JUNBASE.SNG
MORBASE.INS
MORBASE.SNG
WARX1.INS
WARX4.SNG

**Comment by segrax** [comment]
For good measure, you can copy the CF2 amiga audio files into the Dos2_CD folder, and it will replace them too, Amiga uses these files

MORBASE.SNG
MORBASE.INS
INTBASE.SNG
INTBASE.INS
ICEBASE.SNG
ICEBASE.INS
JUNBASE.SNG
JUNBASE.INS
DESBASE.SNG
DESBASE.INS
KILLER.SNG
KILLER.INS
JON.SNG
JON.INS

**Comment by drozumek** [comment]
I'm a little bit confused. I've installed Open Fodder using installer from there
https://github.com/OpenFodder/openfodder/releases
"OpenFodder-Installer-1.5.3.exe"

asked me about Cannon Fodder 1 & 2 PC files so I gave set those from GOG, then asked me about Amiga files, so I set patch to files from there
https://github.com/OpenFodder/openfodder/blob/master/INSTALL.md
Retail Data > Amiga > Option2. WHDLoad > http://www.whdload.de/games/CannonFodder.html
(extracted).
Everything works fine except there are still sounds from PC version (music is from Amiga). 
So I think that you haven't updated installer.exe yet.
I cant do manually changing files you mentioned above because there are no such as directiotier (Dos_CD , Dos2_CD), take a look
https://i.imgur.com/JkZmkv3.png  - gog CF directory
https://i.imgur.com/9hM2spM.png - installed OpenFodder directory

Or I am doing sth wrong?
Best regards

**Comment by segrax** [comment]
Ah,

Yes the installer hasn't been updated yet, but you can download and use the latest built executable from our build pipeline.

On Windows, the installer follows recommended practice and copies the data to your profile directory, %USERPROFILE%/Documents/OpenFodder/Data

The latest EXE is available from
https://s3.amazonaws.com/openfodder-builds/OpenFodder-latest.zip

**Comment by drozumek** [comment]
I don't know what I am doing wrong, but I copied files into Dos_CD folder as you can see here
https://i.imgur.com/gxvCD8i.png
(I only couldn't find WARX1.INS and WARX4.SNG files, there are no such files on CF amiga disc 1,2 or 3)
but there are still sounds from PC version.

I need to mention that I used latest executable files that you recommended.

**Comment by drozumek** [comment]
Ok, I managed to get amiga files and put them into Dos_CD folder. But I've noticed a small-big difference. On Amiga there are sounds of river when you are near it (rjp.JUNBASE(5).wav). There are also sounds of creaky ice on winter missions (rjp.ICEBASE(4).wav) and much more. These sounds were not initially implemented on PC version, and can't hear them after replacing all those files you provided. 
Is there any way to implement these extra environment sounds in PC version? After that is done the best possible Cannon Fodder experience will be achieved.
Best regards

**Comment by segrax** [comment]
Those sounds are part of the 'background tracks', did you copy both sets of files over ?

both .SNG and .INS

**Comment by drozumek** [comment]
Yes, that's how the folder now looks like
https://i.imgur.com/q6NOMO0.png

and I have one more, small question. Why there are files in Dos2_CD  by default
https://i.imgur.com/9OQV04L.png
and in Dos_CD are not?

**Comment by segrax** [comment]
> 
> 
> Yes, that's how the folder now looks like
> https://i.imgur.com/q6NOMO0.png
> 
> and I have one more, small question. Why there are files in Dos2_CD by default
> https://i.imgur.com/9OQV04L.png
> and in Dos_CD are not?

Are you using latest exe from https://s3.amazonaws.com/openfodder-builds/OpenFodder-latest.zip (it should be modified within the last couple of hours)?


If you selected your GOG version of Cannon Fodder 2 during installation, it will have copied the files into the Dos2_CD folder for you automatically

**Comment by drozumek** [comment]
Yes. I use latest exe. 
I've also selected GOG CF 1 during installation but only CF 2 files were copied.

**Comment by segrax** [comment]
CF1 only needs CF_ENG.DAT which has been copied over, it contains all the dos files

**Comment by drozumek** [comment]
Thank you for your replies, I appreciate that. 
I will wait for the new installator, because after copying both .SNG and .INS files, there are sounds from amiga (shooting, enemies yelling etc), but there are no additional ambient sounds (river, wind, ice).

I've noticed one more difference between amiga and PC. PC has something wrong with response time and framerate. Amiga version is much smoother and pointer works better. It was even noticed by some youtubers, eg. https://youtu.be/Os35Y7SFi7Q?t=9m5s
(from 9:14 is amiga version).
Is it possible to fix that in near future? Have you got patronite or sth so I can support you in some way?
best regards

**Comment by segrax** [comment]
> I've noticed one more difference between amiga and PC. PC has something wrong with response time and framerate. Amiga version is much smoother and pointer works better

Do you mean you notice it happening under OpenFodder, or the original dos version?
OpenFodder should run smooth like the Amiga version at all times, if you do notice a specific time a problem occurs, are you able to document it for us?

**Comment by drozumek** [comment]
I noticed it both in original and OpenFodder.
Sure I will document this.
