### ISSUE TITLE
Saves aren't working

### ISSUE THREAD

**Issue by daninthemix** [OpenFodder/openfodder#40]
I just played through 10 missions of Cannon Fodder 1, saving after every mission, and when I went to load there were no saves. Sure enough the C:\Users\Dan\Documents\OpenFodder\Saves folder is empty. :(

**Comment by segrax** [comment]
Hey Dan,

Is this the latest release (1.5.3), or the latest build?

Also, would it  be possible to try Saving, then immediately head to Load and see if any games are showing?

**Comment by segrax** [comment]
But, apologies for losing your game state, i know that really sucks.

**Comment by daninthemix** [comment]
It's a recent build (you linked to this exe in the 'SVGA Mode' ticket). If I save and then immediately load there's nothing there. Am I right in thinking to save you just type your filename and hit enter?

**Comment by segrax** [comment]
alright, so far I havn't been unable to replicate your original issue, 

but a bug did exist when saving and immediately trying to load, the new game wasn't showing until reloading OpenFodder, that was a regression from the path/resource management change back a month or so ago.

can you take a look in the directory with the EXE for any data/save folders?

**Comment by daninthemix** [comment]
There's no data or save folders (or indeed any folders) within the EXE folder. Does OpenFodder store the save folder location anywhere (registry etc) so I can check its correct?

I deleted all the existing saves from that folder the other day, as I wanted to start fresh, and at that time they were certainly showing up when I went to Load game. But the not saving bug may still be new to this build that I'm using, as those save files were created with an older build.

Thanks

**Comment by daninthemix** [comment]
OK weird, it seems to be working now - if I close the game and re-open it, the new saves I've just made are there, but only if I close and re-open, and all the saves I made during yesterday are nowhere to be found.

Odd

**Comment by segrax** [comment]
> There's no data or save folders (or indeed any folders) within the EXE folder. Does OpenFodder store the save folder location anywhere (registry etc) so I can check its correct?

By default, it uses Documents\OpenFodder\Saves then drops back to the directory with the executable, it can/will use both at once if it finds data/saves in both locations.

Aside from that, you can add additional directories to check in the INI file if you want/need them


> I deleted all the existing saves from that folder the other day, as I wanted to start fresh, and at that time they were certainly showing up when I went to Load game. But the not saving bug may still be new to this build that I'm using, as those save files were created with an older build.

Saves should be compatible with versions going back to 1.5.0, thats when we switched to using JSON
 
> 
> OK weird, it seems to be working now - if I close the game and re-open it, the new saves I've just made are there, but only if I close and re-open, and all the saves I made during yesterday are nowhere to be found.
> 
> Odd

Thats the bug I just fixed, should be ok in: https://s3.amazonaws.com/openfodder-builds/OpenFodder-Release-latest.zip

**Comment by daninthemix** [comment]
That's exactly the same size as the one I have now (1,388,544 bytes) but I'll give it a go anyway :)

**Comment by segrax** [comment]
Can check the about screen, it should match these

![image](https://user-images.githubusercontent.com/1327406/57847659-53af7000-781a-11e9-84c4-51fdd5720c26.png)

**Comment by daninthemix** [comment]
I've got to the final phase of the final mission, and saves are working fine, so I'm closing this.
