### ISSUE TITLE
Final phase of final mission (CF1) crashes

### ISSUE THREAD

**Issue by daninthemix** [OpenFodder/openfodder#41]
OpenFodder crashes at the beginning of the final phase of the final mission (Deathtasticelastic). The screen fades in, scrolls to the right, then crashes.

I've reloaded my latest save, F10 ended phase my way to the last phase twice, and every time it crashes.

This also happens if I skip straight to it with the -m 24 -p 6 parameters.

**Comment by segrax** [comment]
just pushed a fix for this, new build should be available within about 5minutes

**Comment by daninthemix** [comment]
Thanks :)
