### ISSUE TITLE
Prevent friendly teammates from using rockets/grenades when left alone

### ISSUE THREAD

**Issue by andrew-mcmahon** [OpenFodder/openfodder#49]
Remember that fun time when you left your teammates with a stash of 6 grenades + 4 rockets which you needed to win the mission - but they decide to fire them all at something relatively harmless and/or blow themselves up in the process?

I wouldn't mind seeing this as a option that could be toggled on or off.
Granted it was part of the charm of the game - perhaps it's heresy to even suggest the change - but it could get a little bit annoying at times.
A slightly iffy workaround was to load all/most of the munitions onto a single man but then you were stuffed if he took a rocket to the face.

**Comment by drnovice** [comment]
Never worried about that... if you don't want to risk AI using rockets/grenades, just don't leave them to it, right?!?

**Comment by andrew-mcmahon** [comment]
...Ugh...Maybe.
As a bit of a extra challenge I always tried to make Jules and Jops make it to the end.
The rocket soldiers blast you to bits when you have a party of four or five tailing behind especially on ice.
Split off a man and you can go on a suicide charge with a novice grunt - pretty satisfying when it works. Plus higher ranked soldiers get little bonuses to shooting range, etc.  
Did you let all your soldiers get shot to bits @drnovice? I'm not serving in your army =P

**Comment by segrax** [comment]
This would probably be implemented somewhere around
https://github.com/OpenFodder/openfodder/blob/master/Source/Fodder.cpp#L10013

**Comment by drnovice** [comment]
> 
> 
> ...Ugh...Maybe.
> As a bit of a extra challenge I always tried to make Jules and Jops make it to the end.
> The rocket soldiers blast you to bits when you have a party of four or five tailing behind especially on ice.
> Split off a man and you can go on a suicide charge with a novice grunt - pretty satisfying when it works. Plus higher ranked soldiers get little bonuses to shooting range, etc.
> Did you let all your soldiers get shot to bits @drnovice? I'm not serving in your army =P

Lol... no I don't leave my soldiers in one team with the tail, nor with some explosive stuff alone... they're like babies and you shouldn't allow them to hurt themselves  ;o)
