### ISSUE TITLE
Build on Raspberry Pi

### ISSUE THREAD

**Issue by actraiser30** [OpenFodder/openfodder#50]
Hello, im tryinf to buid this on raspberry pi in raspbian but i get warning en errors and the compilation fails in the end with 16 errors

is there instructions to compile it? i cannot seem to find any

thank you

**Comment by kordoz** [comment]
I have successfully compiled OpenFodder on Raspberry Pi 4B 8GB ram on Ubuntu Mate 22.04 ARM.

git clone https://github.com/OpenFodder/openfodder

cd openfodder

apt-get install clang libsdl2-mixer-dev

vi /home/username???/openfodder/Source/stdafx.hpp

just edit:
#include </usr/include/SDL2/SDL_mixer.h>

make

**Comment by segrax** [comment]
Thanks @kordoz
