### ISSUE TITLE
Amiga Cannon Fodder files not recognized

### ISSUE THREAD

**Issue by kordoz** [OpenFodder/openfodder#52]
Hello!

When I have copied data from Amiga Cannon Fodder disk and run Open Fodder compiled
under Linux Manjaro, I have got these errors when program tries do load files:

Cannon Fodder 2: MAPM71.SPT Unknown MD5: C88DAA9B9985FF5D74CB11B44C438504

Please help

**Comment by segrax** [comment]
Hi kordoz,

The game should still play, it just means you have a version of it which we don't (we only check against 1 specific release from each different release (CF1/CF2/Demos).

We don't really have a solution to this at the moment, as the engine will need some work to detect different versions, you could track down another copy of it (Good Old Games, if you dont mind paying again)

But that aside, you should be fine to play CF2 as it stands

**Comment by kordoz** [comment]
I have tried Windows version and the same Amiga files works! How it is possible?

**Comment by segrax** [comment]
> 
> 
> I have tried Windows version and the same Amiga files works! How it is possible?

Ah, im not really sure what you mean?
