### ISSUE TITLE
Maximize window

### ISSUE THREAD

**Issue by donno2048** [OpenFodder/openfodder#53]
**Is your feature request related to a problem? Please describe.**
I can't maximize the window using the maximize button

**Describe the solution you'd like**
Make it possible to maximize the window

**Comment by segrax** [comment]
Hi,

The button is disabled, I can't recall specifically why.. perhaps @drnovice  can?

But, you can use these keys to achieve the same effect

* F11:   Toggle full screen
* +:     Increase window size
*  -:     Decrease window size
