### ISSUE TITLE
Build is not working on Manjaro Linux

### ISSUE THREAD

**Issue by xcom169** [OpenFodder/openfodder#54]
**Describe the bug**
Build is not working on Manjaro Linux. Not even the AUR package. 

**To Reproduce**
1. Go to '...'  Source folder
2. Click on '....'  make 
3. Scroll down to '....' to the log

[ 54%] Building CXX object CMakeFiles/openfodder.dir/Source/Parameters.cpp.o
In file included from /mnt/HDD100/Letoltesek/openfodder/Source/Parameters.cpp:25:
/mnt/HDD100/Letoltesek/openfodder/Source/Utils/cxxopts.hpp: In member function ‘void cxxopts::values::detail::SignedCheck<T, true>::operator()(bool, U, const string&)’:
/mnt/HDD100/Letoltesek/openfodder/Source/Utils/cxxopts.hpp:479:42: error: ‘numeric_limits’ is not a member of ‘std’
  479 |             if (u > static_cast<U>(-std::numeric_limits<T>::min()))
      |                                          ^~~~~~~~~~~~~~
/mnt/HDD100/Letoltesek/openfodder/Source/Utils/cxxopts.hpp:479:58: error: expected primary-expression before ‘>’ token
  479 |             if (u > static_cast<U>(-std::numeric_limits<T>::min()))
      |                                                          ^
/mnt/HDD100/Letoltesek/openfodder/Source/Utils/cxxopts.hpp:479:61: error: ‘::min’ has not been declared; did you mean ‘std::min’?
  479 |             if (u > static_cast<U>(-std::numeric_limits<T>::min()))
      |                                                             ^~~
      |                                                             std::min

**Expected behavior**
Exe file should be created. 

**Screenshots**
![image](https://user-images.githubusercontent.com/17802090/124785608-49471780-df47-11eb-827c-d8e4a445af86.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Manjaro Linux

**Comment by laenion** [comment]
With the current version of cxxopts (i.e. https://github.com/jarro2783/cxxopts/blob/master/include/cxxopts.hpp) it is compiling perfectly fine (though I haven't checked whether the source code would need more changes).

**Comment by xcom169** [comment]
Also the 'make' isn't working if the source is not downloaded through git,
but as a zip package.

**Comment by segrax** [comment]
cxxopts has been updated, 

if you like, open another issue for make, but no guarantee i can get to it anytime soon
