### ISSUE TITLE
Flathub

### ISSUE THREAD

**Issue by Mailaender** [OpenFodder/openfodder#58]
Hi, I created a Flatpak package at https://github.com/flathub/flathub/pull/3203

**Comment by segrax** [comment]
Thanks!

**Comment by Mailaender** [comment]
It looks like the package is being rejected though, as compilation relies on older LLVM.

**Comment by segrax** [comment]
is that coming from travis ci ?

**Comment by Mailaender** [comment]
Well no but try updating your https://github.com/OpenFodder/openfodder/blob/master/.travis.yml with latest LLVM and it will spit out numerous warnings and compiler errors.

**Comment by segrax** [comment]
hm, just updated to clang 7 on bionic and its building, there is a few warnings, but it does complete and the unit tests run

https://app.travis-ci.com/github/segrax/openfodder/jobs/572194411

**Comment by Mailaender** [comment]
The current version is https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm13

**Comment by segrax** [comment]
What error are you seeing, just tested it with clang14 and it builds the same


Source/Map/Random.cpp:321:7: warning: unused variable 'result' [-Wunused-variable]
        auto result = pather->Solve(Pos1, Pos2, &path, &totalCost);
             ^
2 warnings generated.
mkdir -p obj
mv *.o obj/
clang++  obj/*.o `sdl2-config --libs` -L/usr/local/lib  -lSDL2_mixer -o Run/OpenFodder

---

clang --version
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by Mailaender** [comment]
What `clang++ --version` did you use?

**Comment by segrax** [comment]
~$ clang++ --version
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
