### ISSUE TITLE
Generating "Random Game" Level -> Another Window Opens -> Crashes To Desktop

### ISSUE THREAD

**Issue by Krnt2007** [OpenFodder/openfodder#60]
I have a Windows 10 machine with (only) the GOG version of the 1st Cannon Fodder game installed.  Running this in OpenFodder works.

Whenever (1) I click on OpenFodder's menu option to play a random game (not just a random level), (2) text appears to indicate all? steps of generating the 1st level of this game have been processed, then (3) an extra small window appears (it appears to be blank with a black background, but it only appears briefly); (4) this new window closes; & (5) OpenFodder crashes to desktop.

**Comment by segrax** [comment]
Hi @Krnt2007 

Is this still occurring?

**Comment by Krnt2007** [comment]
Thanks for asking - I just installed the latest update & random levels generate fine & are playable now.
