### ISSUE TITLE
Android support? Can I play this on my phone? 

### ISSUE THREAD

**Issue by bouncingbenji** [OpenFodder/openfodder#67]

**Comment by segrax** [comment]
Hi @bouncingbenji ,

I don't know if anyone has ever tried it on Android, there is an emscripten build (https://s3.amazonaws.com/openfodder/OpenFodder.html) which should work.

But im happy to merge fixes for Android if anyone wants to make it work

**Comment by bouncingbenji** [comment]
Now if only you could get that as an apk file and mouse support that would be the best thing sliced bread

**Comment by bouncingbenji** [comment]
> Hi @bouncingbenji ,
> 
> I don't know if anyone has ever tried it on Android, there is an emscripten build (https://s3.amazonaws.com/openfodder/OpenFodder.html) which should work.
> 
> But im happy to merge fixes for Android if anyone wants to make it work

Now if only you could get that as an apk file and mouse support that would be the best thing sliced bread
