### ISSUE TITLE
Flatpak Metadata headline says the game is OpenTyrian instead of OpenFodder

### ISSUE THREAD

**Issue by sk-dwtoulouse** [OpenFodder/openfodder#68]
**Describe the bug**
The headline of the Flatpak on Flathub says "An open-source port of the DOS shoot-em-up Tyrian."

**To Reproduce**
1. Go to 'https://flathub.org/fr/apps/org.openfodder.OpenFodder'
2. Read the description headline.

**Expected behavior**
It should read "An open-source port of the DOS strategy game Cannon Fodder."

**Comment by segrax** [comment]
Thanks @sk-dwtoulouse, 

this actually belongs over at flatpak,
but I've submitted a PR for it anyway,
https://github.com/flathub/org.openfodder.OpenFodder/pull/1
