### ISSUE TITLE
Flatpak release

### ISSUE THREAD

**Issue by Huehnergott** [OpenFodder/openfodder#72]
Hello, is there a FlatPak release of 1.8 available? If yes, where? If no, can anyone provide it? Thx alot and keep going!

**Comment by segrax** [comment]
Hey,

I've just submitted a PR for it (https://github.com/flathub/org.openfodder.OpenFodder/pull/2)

You can install the new build with
```sh
flatpak install --user https://dl.flathub.org/build-repo/43946/org.openfodder.OpenFodder.flatpakref
```

**Comment by Huehnergott** [comment]
merci
