### ISSUE TITLE
Save does NOT work

### ISSUE THREAD

**Issue by zWhdmB5T** [OpenFodder/openfodder#74]
**Desktop**
* openSUSE Leap 15.5, thus Linux
* flatpak install https://dl.flathub.org/build-repo/43946/org.openfodder.OpenFodder.flatpakref (as stated in [Issue #72 ](https://github.com/OpenFodder/openfodder/issues/72) for version 1.8.0 as FlatPak), thus FlatPak

**Bug**
Save does NOT work.

**To Reproduce**
1. In main menu window choose Save
2. Save

**Expected behaviour**
1. In main menu window choose Load
2. Possible to choose a Save
3. But: no Saves shown at at

**Comment by segrax** [comment]
Presumably this is pathing related, i don't use flatpak so i'm unable to check it myself
according to one of the configs here

--env=XDG_DATA_DIRS=/app/extra/:/app/share

OF uses XDG_DATA_DIRS, so it might be worth checking to see if /app/extra/OpenFodder and/or /app/share/OpenFodder exist, and perhaps create one of them
