### ISSUE TITLE
[Question] How does the engine caulculate refresh rate speed for the scrolling sequences?

### ISSUE THREAD

**Issue by vanfanel** [OpenFodder/openfodder#77]
Hi there,

I have noticed that, although the engine provides smooth scrolling sequences like the Amiga version, they still show some occasional stuttering (=juddering), both using near-60Hz or 50Hz modes.

So I am trying to understand how the engine calculates the refresh speed for these sequences, in order to fix the small problem.

Can you please give a hand here?

Thanks!

**Comment by segrax** [comment]
Hey @vanfanel,

There is no calculation of refresh speed anymore during these sequences, it was all removed in the last update and we now just use SDL_RENDERER_PRESENTVSYNC 

SDL_RenderPresent blocks until VSYNC occurs, which is called via mFodder->Video_SurfaceRender


This does however mean, if your running in 30Hz, the intro will be twice as slow as when your in 60Hz

**Comment by vanfanel** [comment]
@segrax Thanks a lot for taking the time to explain it to me. 
I saw that effectively you block on SDL_RenderPresent() in  https://github.com/OpenFodder/openfodder/blob/642d4cc70d6390280f5af93880461aa961538c2a/Source/Window.cpp#L295

That's the way to go: That should guarantee totally smooth scroll, as it's the same thing that is done on the Amiga.

However, these small stutters during the helicopter sequence are still present (one must look closely to see them).

I tried disabling the audio code, and that made no difference.
Tried disabling the waiting code in this function, too: https://github.com/OpenFodder/openfodder/blob/642d4cc70d6390280f5af93880461aa961538c2a/Source/Fodder.cpp#L16398
...but that didn't make the occasional stutter go away.

My only guess is that some value around here could be adjusted:
https://github.com/OpenFodder/openfodder/blob/642d4cc70d6390280f5af93880461aa961538c2a/Source/Fodder.cpp#L3516
...But I am stabbing in the dark, because I don't quite understand those values or how they relate to the scrolling.

**Comment by vanfanel** [comment]
Ok! I have noticed the problem better. ONLY the second layer is affected by the stuttering: all the other layers seem to be unaffected. That rules out a general timing issue!

I just compared against the Amiga game on the MiSTer FPGA, and there's no stuttering on the second layer: all the layers scroll smoothly with no stuttering.

Now, @segrax, can you point me to the variable that controls the speed of the second layer? (I mean the second layer from the bottom).

Must be something in https://github.com/OpenFodder/openfodder/blob/642d4cc70d6390280f5af93880461aa961538c2a/Source/Amiga/Graphics_Amiga.cpp#L1498

Found it: This is the variable that controls the increment in the middle layer (the only layer affected by the stuttering): https://github.com/OpenFodder/openfodder/blob/642d4cc70d6390280f5af93880461aa961538c2a/Source/Amiga/Graphics_Amiga.cpp#L1564

**Comment by vanfanel** [comment]
Found the problem. Odd numbers are bound to cause the stuttering I am seeing because there's an even number of positions.

Here's a PR fixing the problem and making all the layers scroll as perfectly smooth as they do on Amiga:

https://github.com/OpenFodder/openfodder/pull/79

Please merge :dancing_men:
