### ISSUE TITLE
Lock cursor to window

### ISSUE THREAD

**Issue by Brakker643** [OpenFodder/openfodder#80]
It would be nice to be able to lock the cursor to the window as there is a lot of edge of window activity for moving the camera, shooting enemies as early possible or clicking on the map.

**Comment by segrax** [comment]
Thanks, 

great idea, and I've just committed it in commit [1500](https://github.com/OpenFodder/openfodder/commit/8c5789ab2b578224c589ae0e3cc7603019e56f3e).

Default setting can be set via the INI, and state toggled with F12 in game.
