### ISSUE TITLE
[Feature Request] Disable pre-scaling

### ISSUE THREAD

**Issue by vanfanel** [OpenFodder/openfodder#81]
**Is your feature request related to a problem? Please describe.**
Lately, I have been playing OpenFodder and other free engines with vkBasalt (https://github.com/DadSchoorse/vkBasalt.git) so I can apply some shaders to it.
Thing is, most of the shaders look pretty bad with the pre-scaled OpenFodder graphics.

**Describe the solution you'd like**
I would like an option that simply renders the 320x200 game texture to a fullscreen window, without the pre-scaling, as many SDL2 engines do.

**Describe alternatives you've considered**
Since the game creates a (320x200)*5 = 1600x1000 window here (I use a 1920x1080p display), I can manually pass the 1600x1000 dimensions to the vkBasalt shader and it looks ok-ish, but scanlines are lost because of the massive size of the shader if those dimenions are passed.

**Comment by segrax** [comment]
Hey @vanfanel,

Not sure if im correctly understanding your feature request, but are you after something that looks like this?

![image](https://github.com/OpenFodder/openfodder/assets/1327406/87d8adf7-1b01-4457-bfde-af90e4eb5983)

**Comment by vanfanel** [comment]
@segrax Hey Robert!
Almost: take that unscaled image, and let SDL2 upscale it automatically to the full dimensions of the window. Don't pre-scale it: let SDL2 do it.

**Comment by segrax** [comment]
@vanfanel  Hey Manuel
We're not pre-scaling, we present the 320x200 (or 320x240) image to SDL_RenderCopy in cWindow::RenderAt, which uses these params to size the final image in the window

```
	Src.w = mScreenSize.mWidth;    // 320
	Src.h = mScreenSize.mHeight;   // 200 (or 240)
	Src.x = (int) 16;
	Src.y = (int) 16;

	Dest.w = GetWindowSize().mWidth;   // Window Width
	Dest.h = GetWindowSize().mHeight;  // Window Height
```

**Comment by vanfanel** [comment]
@segrax 

What I purpose here is an option to have aspect-correct image (4:3, even if the game is 320x200, it was presented in 4:3 on CRT monitors and TVs) but with non-integer scaling, thus using the whole monitor height.

For example, at `RenderAt()`:
```

void cWindow::RenderAt( cSurface* pImage ) {                                                                                                     
        SDL_Rect Src, Dest;                                                                                                                      
                                                                                                                                                 
        Src.w = mScreenSize.mWidth;                                                                                                              
        Src.h = mScreenSize.mHeight;                                                                                                             
        Src.x = (int) 16;                                                                                                                        
        Src.y = (int) 16;                                                                                                                        
                                                                                                                                                                                                                                                                                         
        SDL_GetWindowSize(mWindow, NULL, &Dest.h);                                                                                               
        Dest.w =Dest.h*(float)(4.0/3.0);                                                                                                                      
                                                                                                                                                 
        if (mWindowMode) {                                                                                                                       
                Dest.x = 0;                                                                                                                      
                Dest.y = 0;                                                                                                                      
        }
        else {                                                                                                                                   
                SDL_DisplayMode current;                                                                                                         
                SDL_GetCurrentDisplayMode(0, &current);                                                                                          
                                                                                                                                                 
                Dest.x = (current.w - Dest.w) / 2;                                                                                               
                Dest.y = (current.h - Dest.h) / 2;                                                                                               
        }                                                                                                                                        
                                                                                                                                                 
        SDL_RenderCopy( mRenderer, pImage->GetTexture(), &Src, &Dest );
```

In `InitWindow()` it should be `SDL_SetHint( SDL_HINT_RENDER_SCALE_QUALITY, "linear" );` instead of `SDL_SetHint( SDL_HINT_RENDER_SCALE_QUALITY, 0 );`, when the non-integer scaling option is active. This is to avoid shimmering because of losing the integer scaling.

The problem (it's something about the SDL textures declaration, but I can't remember what) is that using bilinear filtering causes a garbled column on the left side of the screen in-game.

Note this theorical non-integer scaling option is interesting for post-processing shaders: the game looks too blurry without them.

**Comment by segrax** [comment]
@vanfanel 

Regarding the garbled column, not sure if this is intentional or an SDL bug, but the linear scaling is based on the entire source texture, before its copied to the renderer.

This is causing an issue as an area of the map larger than the visible screen is rendered, including under the sidebar
if you look closely in game, you'll notice a Bird fly under the sidebar, then pass in the garbled column.

Anyway; I've just pushed a fix for that

**Comment by segrax** [comment]
As far the rest, while I don't have an issue with it, 

I'm not going to have the time to make the required changes to make it work & polish it

**Comment by vanfanel** [comment]
@segrax I did a PR for this:

https://github.com/OpenFodder/openfodder/pull/82
