### ISSUE TITLE
Garbled upper line

### ISSUE THREAD

**Issue by vanfanel** [OpenFodder/openfodder#83]
**Describe the bug**
A garbled line appears sometimes on the upper part of the screen, showing graphics that do not correspond to any part of the visible game area.
Possibly a fix similar to this would solve it? --> https://github.com/OpenFodder/openfodder/commit/d3556790301494cada524e9fd76e3a28da16b357

I recorded a video of the issue:

https://github.com/OpenFodder/openfodder/assets/837585/f35153f7-2169-47cb-bb35-de826c5adfbe

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 12
 - Version 12

**Comment by segrax** [comment]
Yep, same problem. Thanks!
Just pushed a fix
