### ISSUE TITLE
Add a way to get back to boot hill

### ISSUE THREAD

**Issue by tremby** [OpenFodder/openfodder#88]
**Is your feature request related to a problem? Please describe.**
The only way I can find to get back to boot hill (for example to load game) from a mission title screen or the game is to quit the whole application and then start it again.

**Describe the solution you'd like**
I'd like to be able to press some key to go back to boot hill. Or if that's not possible for whatever reason, to go directly to the load game screen.

**Describe alternatives you've considered**
Escape, but this just restarts the level.
Quitting the whole app and restarting it does the job.

**Additional context**

**Comment by segrax** [comment]
Hi @tremby,

If you push escape on the mission title screen, it will return you to the boothill screen. Likewise, hitting escape on the boothill screen, will return you to the campaign selection screen

**Comment by tremby** [comment]
So it does. I thought I'd tried that. Thanks.
