### ISSUE TITLE
1.9.0 fails to build with libc++

### ISSUE THREAD

**Issue by jbeich** [OpenFodder/openfodder#90]
Regressed by 007523136ab4 via `std::thread`. Affects Clang/libc++ and GCC/libc++ but not GCC/libstdc++. On Linux `-stdlib=libc++` may be required to reproduce (haven't tested).

To work around add `-lpthread`. Probably not valid for macOS, Windows or even Android, so would need to be abstracted e.g., with CMake: `find_package(Threads)` + `target_link_libraries(openfodder Threads::Threads)`.

```c++
$ make
[...]
ld: error: undefined symbol: pthread_create
>>> referenced by Start.cpp
>>>               obj/Start.o:(std::__1::thread::thread<void (cFodder::*)(), std::__1::shared_ptr<cFodder>&, void>(void (cFodder::*&&)(), std::__1::shared_ptr<cFodder>&))

$ cmake -G Ninja
$ cmake --build .
[...]
ld: error: undefined symbol: pthread_create
>>> referenced by Start.cpp
>>>               CMakeFiles/openfodder.dir/Source/Start.cpp.o:(std::__1::thread::thread<void (cFodder::*)(), std::__1::shared_ptr<cFodder>&, void>(void (cFodder::*&&)(), std::__1::shared_ptr<cFodder>&))

$ c++ --version
FreeBSD clang version 18.1.6 (https://github.com/llvm/llvm-project.git llvmorg-18.1.6-0-g1118c2e05e67)
Target: x86_64-unknown-freebsd15.0
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by segrax** [comment]
ive pushed both changes, but am unable to test them right now

**Comment by jbeich** [comment]
I confirm, builds fine (both make and cmake). Only tested on FreeBSD (13.2 amd64, 13.2 i386, 15.0 amd64).

**Comment by segrax** [comment]
Thank you!
