### ISSUE TITLE
Enable TLS

### ISSUE THREAD

**Issue by bentley** [OpenFodder/openfodder#92]
Visiting https://openfodder.com/ leads to a certificate error, as GitHub serves a certificate only valid for GitHub subdomains.

Since 2018, GitHub has supported TLS for custom domains by hosting sites on a CDN. This means [updating the DNS records for openfodder.com](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/#configuring-your-domain) should be enough to automatically enable TLS via Let’s Encrypt.

**Comment by segrax** [comment]
Thanks!

TLS is now enabled and enforced
